version: '3'

services:
  homolog.api:
    build: .
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
  production.api:
    build: .
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017