version: 2.1
orbs:
  kube-orb: circleci/kubernetes@0.10.1
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASS" | docker login celonet.azurecr.io --username $DOCKER_USER --password-stdin
      - run: docker build -t campanhabrinquedo-api:$CIRCLE_BUILD_NUM .
      - run: docker tag campanhabrinquedo-api:$CIRCLE_BUILD_NUM celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BUILD_NUM
      - run: docker push celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BUILD_NUM
  deploy:
    machine: true
    steps:
      - checkout
      - kube-orb/install
      - run:
          name: Deploy app to kubesail
          command: |
            kubectl config set clusters.$CLUSTER_NAME.server $KUBE_CLUSTER_SERVER
      - run: kubectl config set clusters.$CLUSTER_NAME.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
      - run: kubectl config set users.$CLUSTER_NAME-admin.client-key-data "$KUBE_CLIENT_KEY"
      - run: kubectl config set-context $KUBE_CLUSTER_SERVER --namespace=$DOCKER_USER --cluster=$KUBE_CLUSTER_SERVER --user=$KUBE_CLUSTER_SERVER
      - run: kubectl config set-context $KUBE_CLUSTER_SERVER
      - run: pwd && kubectl apply -f ./project/kubernetes/

workflows:
  version: 2            
  campanha_workflow:
    jobs:
      - build
      - deploy:
          requires: 
            - build

