version: 2.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t campanhabrinquedo-api:$CIRCLE_BRANCH .
      - run: docker tag campanhabrinquedo-api celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BRANCH
      - run: docker push celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BRANCH
      - run:
          name: Deploy app to kubesail
          command: |
            echo "deploy"
