version: 2.0
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t campanhabrinquedo-api .
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker tag campanhabrinquedo-api celonet.azurecr.io/campanhabrinquedo-api:1.0.${CIRCLE_BUILD_NUM}
            docker push celonet.azurecr.io/campanhabrinquedo-api:1.0.${CIRCLE_BUILD_NUM}
      - run:
          name: Deploy app to kubesail
          command: |
            echo "deploy"
