version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.10.1
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASS" | docker login celonet.azurecr.io --username $DOCKER_USER --password-stdin
      - run: docker build -t campanhabrinquedo-api:$CIRCLE_BUILD_NUM .
      - run: docker tag campanhabrinquedo-api:$CIRCLE_BUILD_NUM celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BUILD_NUM
      - run: docker push celonet.azurecr.io/campanhabrinquedo-api:$CIRCLE_BUILD_NUM
  deploy:
    machine: true
    steps:
      - kube-orb/install-kubectl
      # - kube-orb/install-kubeconfig:
      #   kubeconfig: KUBECONFIG
      # - kube-orb/create-or-update-resource:
      # - run:
      #     name: Deploy app to kubesail
      #     command: |
      #       ./kubectl \
      #       --kubeconfig=/dev/null \
      #       --server=$KUBERNETES_SERVER \
      #       --certificate-authority=cert.crt \
      #       --token=$KUBERNETES_TOKEN \
      #       apply -f ./kubernetes/

workflows:
  version: 2            
  campanha_workflow:
    jobs:
      - build
      - deploy:
          requires: 
            - build

