apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  namespace: celonet
  generation: 3
  labels:
    run: campanhabrinquedo-api
  name: campanhabrinquedo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: campanhabrinquedo-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: campanhabrinquedo-api
    spec:
      containers:
      - env:
        - name: TZ
          value: GMT
        image: celonet.azurecr.io/campanhabrinquedo-api:latest
        name: campanhabrinquedo-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: regcred        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30